receivers:
  filelog:
    include: [ /var/log/nginx/*.log ]

processors:
  batch:
  externaljson:
    local: true
    metadata_paths: 
      - hostname
      - instance-id
      - placement/availability-zone
      - placement/region
      - public-ipv4

exporters:
  kafka:
    brokers:
      - kafka-us-east-1.utibeumanah.dev:9092
    protocol_version: 2.0.0
    encoding: json

service:
  pipelines:
    logs:
      processors: [externaljson]
      receivers: [filelog]
      exporters: [kafka]
  