dist:
  name: otelcol
  description: Basic OTel Collector 
  output_path: ./otelcol

exporters:
  - gomod:
      # NOTE: Prior to v0.86.0 use the `loggingexporter` instead of `debugexporter`.
      go.opentelemetry.io/collector/exporter/debugexporter v0.101.0
  - gomod:
      go.opentelemetry.io/collector/exporter/otlpexporter v0.101.0
  - gomod:
      github.com/open-telemetry/opentelemetry-collector-contrib/exporter/kafkaexporter v0.102.0

processors:
  - gomod:
      go.opentelemetry.io/collector/processor/batchprocessor v0.101.0
  - gomod:
      github.com/utibeabasi6/cloudflare-logging/otel/otelcol/processors/externaljsonprocessor v0.0.0

receivers:
  - gomod:
      go.opentelemetry.io/collector/receiver/otlpreceiver v0.101.0
  - gomod:
      github.com/open-telemetry/opentelemetry-collector-contrib/receiver/filelogreceiver v0.102.0

replaces:
- github.com/utibeabasi6/cloudflare-logging/otel/otelcol/processors/externaljsonprocessor => ./processors/externaljsonprocessor