receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
  externaljson:
    local: true
    metadata_paths: 
      - hostname
      - instance-id
      - placement/availability-zone
      - placement/region
      - public-ipv4

exporters:
  kafka:
    brokers:
      - localhost:19092
    protocol_version: 2.0.0

service:
  pipelines:
    logs:
      processors: [externaljson]
      receivers: [otlp]
      exporters: [kafka]
  