name: Configure minions

on:
    workflow_dispatch: 
      inputs:
        filter:
          description: 'Minion Filter'
          required: true
          default: 'all'
          type: choice
          options:
            - all
            - app
            - kafka

jobs:
    accept-keys:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Accept minion keys
              uses: appleboy/ssh-action@v1.0.3
              with:
                host: ${{ secrets.SALT_MASTER_HOSTNAME }}
                username: ${{ secrets.SALT_MASTER_USERNAME }}
                key: ${{ secrets.SSH_PRIV_KEY }}
                script: sudo salt-key -A
    
    config-kafka:
        runs-on: ubuntu-latest
        needs: accept-keys
        if: inputs.filter == 'all' || inputs.filter == 'kafka'
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Configure kafka instances
              uses: appleboy/ssh-action@v1.0.3
              with:
                host: ${{ secrets.SALT_MASTER_HOSTNAME }}
                username: ${{ secrets.SALT_MASTER_USERNAME }}
                key: ${{ secrets.SSH_PRIV_KEY }}
                script: sudo salt 'kafka-*' test.ping
    
    config-app:
      runs-on: ubuntu-latest
      needs: accept-keys
      if: inputs.filter == 'all' || inputs.filter == 'app'
      steps:
          - name: Checkout
            uses: actions/checkout@v4
          - name: Configure app instances
            uses: appleboy/ssh-action@v1.0.3
            with:
              host: ${{ secrets.SALT_MASTER_HOSTNAME }}
              username: ${{ secrets.SALT_MASTER_USERNAME }}
              key: ${{ secrets.SSH_PRIV_KEY }}
              script: sudo salt 'app-*' test.ping
      