name: Deploy Salt States

on:
    workflow_dispatch: 

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Copy salt states to master
              uses: appleboy/scp-action@v0.1.7
              with:
                host: ${{ secrets.SALT_MASTER_HOSTNAME }}
                username: ${{ secrets.SALT_MASTER_USERNAME }}
                key: ${{ secrets.SSH_PRIV_KEY }}
                source: "salt/**/*"
                target: "/srv/salt"
                rm: true